language: ruby
cache: bundler
env:
  - DB=postgresql
before_install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver*.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
before_script:
  - psql -c 'create database carator_test' -U postgres
  - "export DISPLAY=:99.0" # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
