language: ruby
cache: bundler
env:
  - DB=postgresql
before_install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver*.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
before_script:
  - psql -c 'create database carator_test' -U postgres
script:
  - xvfb-run make test
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
