# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 008067be7704ba563bcfbef40b92b895f79a7ac5442b05cfd8720a303c53986c6ca9807b7ba64dd7365a69e539b9aa622eaec5e214a37ebf697540b81239b881

test:
  secret_key_base: a287c0836c58dc5bf53c99052d95f69b7f6800f812a76fa662b2fd595b4aec6e77390c9c072649dc7cc948000c69f9962d3d64bfd8ef81bf5ba92cc349cabcd9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
